spring:
  application:
    name: inventory-sales-api

  datasource:
    url: jdbc:mysql://localhost:3306/inventory_sales?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: MySecurePass123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 8080

app:
  security:
    jwt:
      secret: bXktc3VwZXItc2VjdXJlLXNlY3JldC1rZXktZm9yLWp3dC1zaWduaW5nLWNoYW5nZS1pbi1wcm9k
      expiration-ms: 3600000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    root: INFO
    com.rodriguez.inventorysales: DEBUG
    org.hibernate.SQL: DEBUG